Water Schedule
MarenOelixtown/plant-care-app pull request #25
Opened 2024-07-11 10:14 UTC by MarenOelixtown

Acceptance criteria

>  Clicking the calender icon takes the user to My Schedule page.
>  Clicking the Add new water schedule button opens a form and get input for plant and start date in a drop down list.
>  Clicking the create button create a new water schedule in the My schedule page. Also displays an alert "New schedule created"
>  The Schedule page displays list of plants and their watering schedule if is set.
>  When there is no entry for schedule, a message is displayed as"No schedule is set. Want to create one?"

2024-07-11 12:33 UTC, F-Kirchhoff requested changes
Hey Plant Care Team!
very nice code already. I like how you use the query option of the router to pass information from one page to another. I mainly have cosmetic suggestions for you to structure your code a bit better. Most of it is optional so please decide for yourself if you find the hints useful or not.

2024-07-11 12:33 UTC, F-Kirchhoff commented on components/MyPlants.js
> +);
The Capstone template is configured in a way, that you can directly import Svgs as Components and use them without the need to create this wrapper yourself:

```js
//CalendarIcon.svg
  <svg
    fill="#000000"
    width="50px"
    height="50px"
    viewBox="-3 0 19 19"
    xmlns="http://www.w3.org/2000/svg"
    className="cf-icon-svg"
  >
    <title>Schedule</title>
    <path d="M11.882 3.187a.476.476 0 0 1 .475.475v11.063a.476.476 0 0 1-.475.475H1.118a.476.476 0 0 1-.475-.475V3.662a.476.476 0 0 1 .475-.475h1.328v.721a1.425 1.425 0 0 0 2.85 0v-.72H7.71v.72a1.425 1.425 0 0 0 2.85 0v-.72zm-.634 3.37H1.752v7.535h9.496zm-7.384.821H2.621V8.67h1.243zm0 2.292H2.621v1.292h1.243zm0 2.292H2.621v1.291h1.243zm.561-8.054V2.475a.554.554 0 1 0-1.108 0v1.433a.554.554 0 1 0 1.108 0zm1.613 3.47H4.794V8.67h1.244zm0 2.292H4.794v1.292h1.244zm0 2.292H4.794v1.291h1.244zm2.174-4.584H6.968V8.67h1.244zm0 2.292H6.968v1.292h1.244zm0 2.292H6.968v1.291h1.244zm1.477-8.054V2.475a.554.554 0 0 0-1.108 0v1.433a.554.554 0 0 0 1.108 0zm.696 3.47H9.142V8.67h1.243zm0 2.292H9.142v1.292h1.243zm0 2.292H9.142v1.291h1.243z" />
  </svg>


// MyPlants.js
import CalendarIcon from './CalendarIcon.svg'

...

<Calendaricon />
```

2024-07-11 12:33 UTC, F-Kirchhoff commented on components/NavigationBar/HomeIcon.js
> +      strokeLinejoin="round"
Maybe you want to apply this trick for all Icons and put them into an Icons folder.

2024-07-11 12:33 UTC, F-Kirchhoff commented on components/Schedule.js
> +  height: 100px;
you could use `aspect-ratio: 1 / 1;` instead setting the height of the image. Not necessary but could be nice.

2024-07-11 12:33 UTC, F-Kirchhoff commented on components/Schedule.js
> +  }, [router.query.success]);
you should not need a useEffect here nor a state, if the router.query element changes, the component should be rerendered anyways:

```js
const router = useRouter();
const successMessage = router.query.success ? "Watering-Schedule added successfully!" : null;
```

2024-07-11 12:33 UTC, F-Kirchhoff commented on components/Schedule.js
> +    .sort((a, b) => new Date(a.wateringDate) - new Date(b.wateringDate));
please use toSorted instead of sort, since it does not mutate the previous array.

2024-07-11 12:33 UTC, F-Kirchhoff commented on components/ScheduleForm.js
> +  isMyPlantFunction,
thats a strange name for a prop, maybe you want to remove the "function" from the name?

2024-07-11 12:33 UTC, F-Kirchhoff commented on components/ScheduleForm.js
> +        onChange={(e) => setSelectedPlant(e.target.value)}
please don't use e, use event instead.

2024-07-11 12:33 UTC, F-Kirchhoff commented on components/ScheduleForm.js
> +        onChange={(e) => setWateringStartDate(e.target.value)}
here as well.

2024-07-11 12:33 UTC, F-Kirchhoff commented on pages/_app.js
> +
this looks very similar to the isMyPlantFunction and isUserPlantFunction. You could simplify all three functions by creating a function called getPlantInfoById which returns the info Object for the respective id. Then you can use the object directly to determine if isUserPlant, isMyPlant or wateringDate exist on it. Then you need to pass only one function down to your Components.

2024-07-11 12:41 UTC, MarenOelixtown commented
Many thanks for your feedback🙏...we will have a look at your hints and come back!

2024-07-12 08:15 UTC, F-Kirchhoff requested changes
Hey Plant Care Team,
this looks fantastic, you could reduce the number of props a lot and simplify your Icons respectively. There are some further suggestions, but they might be quick to resolve.

2024-07-12 08:15 UTC, F-Kirchhoff commented on components/MyPlants.js
> +    (plant) => getPlantInfoById(plant.id)?.isMyPlant
very nice ✨

2024-07-12 08:15 UTC, F-Kirchhoff commented on components/MyPlants.js
> +            const isMyPlant = getPlantInfoById(plant.id)?.isMyPlant;
you can make this shorter and more efficient:
```suggestion
            const plantInfo = getPlantInfoById(plant.id)
            const {isUserPlant, isMyPlant} = plantInfo
```
You can skip the variable "plantInfo" and destructure the return value of getPlantInfoById directly in the first line. You can decide what you find more pleasing.

2024-07-12 08:15 UTC, F-Kirchhoff commented on components/NavigationBar/PlantOverviewIcon.js
> +    <title>Plant Overview</title>
you can change this into a svg file as well and set the fill and stroke directly on the Element after importing. Please update all icons in this way. The name "getFillColor" usually implies that its a function, you could use something like iconColor or fillColor
```js
import PlantOverViewIcon from './plantOverViewIcon.svg'

<PlantOverviewIcon stroke={iconColor} fill={iconColor} />

2024-07-12 08:15 UTC, F-Kirchhoff commented on components/PlantDetails.js
> +  const isUserPlant = getPlantInfoById(plant.id)?.isUserPlant;
here you can do the destructuring trick I mentioned above as well.

2024-07-12 09:21 UTC, MarenOelixtown commented
Thank you Felix, for giving the additional feedback ✌️...finally I followed your suggestions and posted an update 📫

2024-07-12 10:10 UTC, F-Kirchhoff approved these changes
Now its ready 🥳 Great job!

2024-07-12 13:17 UTC, merged